
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Echo", targetNamespace = "http://server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Echo {


    /**
     * 
     * @param msg
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "echoResponse", targetNamespace = "")
    @RequestWrapper(localName = "reply", targetNamespace = "http://server/", className = "client.Reply")
    @ResponseWrapper(localName = "replyResponse", targetNamespace = "http://server/", className = "client.ReplyResponse")
    @Action(input = "http://server/Echo/replyRequest", output = "http://server/Echo/replyResponse")
    public String reply(
        @WebParam(name = "msg", targetNamespace = "")
        String msg);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addResponse", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://server/", className = "client.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://server/", className = "client.AddResponse")
    @Action(input = "http://server/Echo/addRequest", output = "http://server/Echo/addResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

}
